---

- hosts: web_servers
  become: true
  tasks:

  - name: Remove Apache and PHP (Debian)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Debian"

  - name: Remove Apache and PHP (CentOS)
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"



- hosts: db_servers
  become: true
  tasks:

  - name: Remove MariaDB package (Debian)
    apt:
      name: mariadb-server
      state: absent
    when: ansible_distribution == "Debian"

  - name: Remove MariaDB package (CentOS)
    apt:
      name: mariadb
      state: absent
    when: ansible_distribution == "CentOS"



- hosts: file_servers
  become: true
  tasks:

  - name: Remove samba package
    package:
      name: samba
      state: absent
